DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email varchar(255) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT email_at CHECK (email LIKE '%@%'),
    CONSTRAINT space_name_user CHECK (name NOT LIKE ' ' and name NOT LIKE '')
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name),
    CONSTRAINT space_name_categories CHECK (name NOT LIKE ' ' and name NOT LIKE '')
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(1000) NOT NULL,
    category_id        BIGINT        NOT NULL REFERENCES categories (id),
    confirmed_request  BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(1000),
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id          BIGINT        NOT NULL REFERENCES users (id),
    lat                float         NOT NULL,
    lon                float         NOT NULL,
    paid               boolean       NOT NULL,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation boolean       NOT NULL,
    state              varchar,
    title              VARCHAR(1000) NOT NULL,
    views              BIGINT        NOT NULL
)