DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email varchar(255) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT email_at CHECK (email LIKE '%@%'),
    CONSTRAINT space_name_user CHECK (name NOT LIKE ' ' and name NOT LIKE '')
)