DROP TABLE IF EXISTS hit;
DROP TABLE IF EXISTS app;

CREATE TABLE IF NOT EXISTS app
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(255) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app_id    BIGINT                                              NOT NULL,
    uri       VARCHAR(64)                                         NOT NULL,
    ip        VARCHAR(16)                                         NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE not null,
    CONSTRAINT "app_hit_constraint" FOREIGN KEY (app_id) references app (id)
);